### ISSUE TITLE
Breaks with latest version 1.0 of "understeam/yii2-httpclient"

### ISSUE THREAD

**Issue by BAWES** [Understeam/yii2-slack#4]
Love your repo, amazing work!
Just did a `composer update` and turns out that it only works with v0.3 but breaks on v1.0

**Comment by AnatolyRugalev** [comment]
@BAWES it happens because of another library were used from v1.0 (understeam/yii2-httpclient -> yiisoft/yii2-httpclient). I can say more if you provide composer logs. Thanks for feedback!

**Comment by BAWES** [comment]
Thanks for the quick response. For some reason my composer kept downloading an older version until I explicitly defined `yiisoft/yii2-httpclient : dev-master` 

Works perfectly now, thanks!

**Comment by AnatolyRugalev** [comment]
@BAWES If you need more features let me know.
