### ISSUE TITLE
Payload overwrite is missing

### ISSUE THREAD

**Issue by BenasPaulikas** [Understeam/yii2-slack#5]
Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username".

THis is by adding channel attribute to payload

**Comment by AnatolyRugalev** [comment]
Fixed with 4d4612bbd8aa473ddbc4bb89576c156487e8febd

New version tagged: `v0.2.1`

**Comment by AnatolyRugalev** [comment]
Thank you!
