### ISSUE TITLE
Error while installing via composer

### ISSUE THREAD

**Issue by skayt** [Understeam/yii2-slack#6]
Hello I tried to install yii2-slack but I got error below. 

```
$ composer require understeam/yii2-slack:~0.2 --prefer-dist
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for understeam/yii2-slack ~0.2 -> satisfiable by understeam/yii2-slack[v0.2.1].
    - understeam/yii2-slack v0.2.1 requires yiisoft/yii2-httpclient dev-master -> satisfiable by yiisoft/yii2-httpclient[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

Please is there a way to go around this?

**Comment by AnatolyRugalev** [comment]
@DabHands please ensure that you have

``` json
"minimum-stability": "dev"
```

in your `composer.json` configuration. This package is not stable yet.
If this option is already set post here contents of `composer.json`

**Comment by skayt** [comment]
That is what I eventually did. Used "dev-master as 2.0.0" instead of "~2.0.0" inside composer.json. Thank you.

**Comment by AnatolyRugalev** [comment]
If you have any question or ideas, feel free to create issue

**Comment by skayt** [comment]
@AnatolyRugalev I am not clear on the usage please. I have yii2-slack and yii-httpclient installed in my application now, however I cannot move on with the rest of the documentation.

> First of all, configure yiisoft/yii2-httpclient component:
> Where do I configure the component?
> 
> Also you can set it up only inside of slack client:
> I guess you are referring to the Client.php inside yii2-slack?
> 
> Configure component:
> The same component I was dealing with initally?
> 
> Now you can send messages right into slack channel via next command:
> Where do I insert the line of code that followed this instruction?

I am sorry to bother you, I am still learning. If I could solve this myself without creating an issue I would have done that. Thank you.

**Comment by AnatolyRugalev** [comment]
@DabHands 

Add this code to `components` section in your main configuration file. Usually `app/config/main.php` or `common/config/main.php`

```
'components' => [
        'slack' => [
            'class' => 'understeam\slack\Client',
            'url' => '<slack incoming webhook url here>',
            'username' => 'My awesome application',
            'httpclient' => [
                'class' => 'yii\httpclient\Client',
            ],
        ],
    ],
```

If you have no plans to use `httpclient` somewhere except `slack`, you may use above configuration. If you want to use it, you can separate it to two components:

```
'components' => [
        'httpclient' => [
            'class' => 'yii\httpclient\Client',
        ],
        'slack' => [
            'class' => 'understeam\slack\Client',
            'url' => '<slack incoming webhook url here>',
            'username' => 'My awesome application',
        ],
    ],
```

> Now you can send messages right into slack channel via next command:
> 
> > Where do I insert the line of code that followed this instruction?

Anywhere you need to send message from.
